sudo: false
language: node_js
node_js:
  - "stable"
install:
  - npm i
script:
  - npm run test
after_success:
  - npm run coverage
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
